[game]
hostname         = "[100% FREE LAG] Google's Gaggle Land"
desc             = "The gaggle land. Where we go. Have fun yeah."
lobbyenabled     = true
role_timers      = false
soft_max_players = 20

panic_bunker.enabled = false
panic_bunker.min_overall_minutes = 120
panic_bunker.disable_with_admins = true
panic_bunker.enable_without_admins = false
panic_bunker.show_reason = true
panic_bunker.custom_reason = "This server has a panic bunker enabled. Request a whitelist, man!"

# IPIntel stuff
ipintel_enabled = false
ipintel_contact_email = "telecommunications@spacestation14.com"

[infolinks]
github     = "https://github.com/googles-gaggle-land/gaggle-zone"

[net]
max_connections = 1024

[vote]
restart_required_ratio = 0.7

[netres]
limit = 10.0

[admin]
see_own_notes = true
deadmin_on_join = true
new_player_threshold = 600
alert.min_players_sharing_connection = 2
allow_multi_server_play = false

[atmos]
max_explosion_range = 5

[worldgen]
enabled = true

[replay]
auto_record = true
max_compressed_size = 1000000